/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/users": {
    /** ユーザ一覧の取得 */
    get: {
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": string;
          };
        };
      };
    };
  };
  "/users/{userId}": {
    /** ユーザの取得 */
    get: {
      parameters: {
        path: {
          userId: string;
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": string;
          };
        };
      };
    };
    /** ユーザの更新 */
    put: {
      /** @description 更新するユーザ情報 */
      requestBody: {
        content: {
          "application/json": {
            name?: string;
            email?: string;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": string;
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
